### ISSUE TITLE
bash: "nocobbler on" gives errors with flow status and rerun function.

### ISSUE THREAD

**Issue by dyndna** [sahilseth/flowr#13]
default bash options has *noclobber* set to off, allowing `touch hello && echo hi > hello` to work. If  `set -o | grep noclobber` is on, then the same command will return error:

>bash: hello: cannot overwrite existing file

Since user commands as well as flow [torque.sh](https://github.com/sahilseth/flowr/blob/master/inst/conf/torque.sh#L38) and other job scheduler files rely on `>` operator for job trigger, dependency and rerun functions, `set -o | grep noclobber` flag is worth checking before using `>` or do `set +o noclobber && touch hello && echo hi > hello` or force allow overwrite using `touch hello && echo hi >| hello`

PS: `exitstat` variable, currently at https://github.com/sahilseth/flowr/blob/master/inst/conf/torque.sh#L37 needs to be called just after `{{{CMD}}}` line, https://github.com/sahilseth/flowr/blob/master/inst/conf/torque.sh#L33

**Comment by sahilseth** [comment]
Great thanks for the suggestion.

So basically including the set no cobbler option before trigger would make sure that rerun works properly ?

**Comment by dyndna** [comment]
True! See bebe5c7539e6
