### ISSUE TITLE
When creating flow_objet with to_flow command, no output in resulting Rplots.pdf

### ISSUE THREAD

**Issue by dyndna** [sahilseth/flowr#2]
When creating flow_objet with `to_flow` command, no output in resulting Rplots.pdf.

```r
fobj = to_flow(x = user_flow_mat, def = flow_def, platform = myplatform, 
 							 flow_base_path = myoutdir, 
 							 flowname = myflowname, 
 							 execute = myexecute)
```

Resulting pdf can not be viewed in pdf reader, ? no graphics inside pdf.

**Comment by sahilseth** [comment]
I have also seen this empty file being created, but have not been able to identify the cause.

Also, a correct plot is created in: `myoutdir/myflowname.../myflowname-flow_design.pdf` ?

Will note this one down.
