### ISSUE TITLE
Command to specify email alert only for job killed or error.

### ISSUE THREAD

**Issue by dyndna** [sahilseth/flowr#4]
Is there an option while submitting `fobj <- to_flow(...)` command to specify email alert only for job killed or error?

**Comment by sahilseth** [comment]
Yes we have a way for you to specify your email address. By default the cluster will email when the job completes.

Let us get the default format for the platform.

```
queue(platform = "moab")@format
[1] "${SUBMIT_EXE} -N ${JOBNAME} -l nodes=${NODES}:ppn=${CPU} -l walltime=${WALLTIME} -l mem=${MEMORY} -S /bin/bash -d ${CWD} -V -o ${STDOUT} -m ae -M ${EMAIL} -j oe -r y -V ${EXTRA_OPTS} ${CMD} ${DEPENDENCY}"
```

Here are more details on the parameter ( -m ae) from [computing.llnl.gov/tutorials/moab](https://computing.llnl.gov/tutorials/moab)

```
#MSUB -m option(s)
-m option(s)
Defines the set of conditions (a=abort,b=begin,e=end) when the server will send a mail message about the job to the user.
```

### Getting email when jobs exits/completes:

```
## --- create a custom queue object
qobj = queue(platform="moab",  email = "samir@samir.com")
## --- Finally supply this to to_flow()
to_flow(x=flow_mat, def = my_def, qobj = qobj)
```

### Getting email when jobs starts AND exits/completes:

We need to change `-m ae` to `-m bae`
```
## --- create a custom queue object
qobj = queue(platform="moab",  email = "samir@samir.com", 
 format =  "${SUBMIT_EXE} -N ${JOBNAME} -l nodes=${NODES}:ppn=${CPU} -l walltime=${WALLTIME} -l mem=${MEMORY} -S /bin/bash -d ${CWD} -V -o ${STDOUT} -m bae -M ${EMAIL} -j oe -r y -V ${EXTRA_OPTS} ${CMD} ${DEPENDENCY}")

## --- Finally supply this to to_flow()
to_flow(x=flow_mat, def = my_def, qobj = qobj)
```

This flow will send a email after completion of each job in the workflow (may be hundreds...). The email would contain information regarding the exit status (or start). You may want a custom filter in your email client to manage this bulk.

**Comment by sahilseth** [comment]
The easiest way to do this

**Comment by sahilseth** [comment]
In case more changes to are required, copy this (https://github.com/sahilseth/flowr/blob/master/inst/conf/torque.sh) to ~/flowr/conf/torque.sh and edit it to glory.

Here are a few tips on hope a PBS script should look like:
https://computing.llnl.gov/tutorials/moab/
