### ISSUE TITLE
flowr flowdef bug while running scatter-gather approach

### ISSUE THREAD

**Issue by dyndna** [sahilseth/flowr#73]
`scatter-gather` approach is failing with a major bug in `flowr` code.

In brief: bug was found while doing scatter-serial to parallelize  GATK steps: `index_7`, `recal_8`, `bqsr_9` and `run_mutect`,  by chromosomes. flowr currently does not respect one-to-one relationship for successive scatter-serial jobs, and instead will start successive scatter jobs without making sure that preceding completed job is one matched to current job and not a different one, e.g., If `indel_8` for chromsome 22 is complete, flowr should start `recal_8` for same chr 22 but instead it can start other chromosome(s) even though `indel_8` might be running for the latter chromosome(s).

Issue stems from faulty `flowmat` which assigns the same dependency job ID for HPC job scheduler as the first job of scatter-serial instead of respecting one-to-one relationship between consecutive scatter-serial jobs.

This issue has been cross-referenced from internal code repository and work in progress to fix it.
#### Temporary fix:

Disallow scatter-serial and force to use `scatter-gather` instead, i.e., all jobs of scatter have to be completed before next scatter job can start.

**Comment by sahilseth** [comment]
Thanks for putting this together, Samir.

I will make scatter-gather into a warning.

**Comment by dyndna** [comment]
See related fix for HPC using `moab` or `sge` scheduler at https://github.com/sahilseth/flowr/pull/74: This fix is relevant for workflow using scatter-gather approach **and** using multiple job ids as dependencies for a next job to be executed. 

There is no issue with respect to flowdef for scatter-gather if job dependency involves only one job. 

There is a open issue with `flowr status` command and resulting *flowmat* file, where jobs ids are not correctly aligned as per scatter-gather relationship, e.g., job id for *recalibration step for chromosome 2* should be tied to *indel step for chromosome 2* before and not to *indel step for chromosome 12* or other chromosome. This does **not** impact submitted jobs as the latter do correctly orders jobs ids, e.g., chr1 to chr1, chr10 to 10, etc. 

**PS:** Although untested, such faulty *flowmat* and *flow_details.rds* resulted from `flowr status` may impact rerunning the workflow using `flowr rerun` command.
