### ISSUE TITLE
sge conf should be pbs?

### ISSUE THREAD

**Issue by shjoshi** [sahilseth/flowr#76]
This is really a minor point. But should conf/sge.sh be renamed conf/pbs.sh?
A new configuration file can be added for sge.sh that has SGE tailored commands. 
SGE commands/variables start with a SGExxx.

**Comment by sahilseth** [comment]
This is an interesting point. Torque, SLURM, SGE and MOAB all accept PBS directives. There is major overlap between all these configuration files. I have files named after scheduler, so we may not need a file called pbs.sh

https://www.glue.umd.edu/hpcc/help/slurm-vs-moab.html

The nice aspect of these configuration files is that you can place them in `~/flowr/conf` and customize to glory. Additionally, I am open to pull requests with more customized examples of SGExxx directives. I do not have easy access to an SGE cluster, so may not be able to test it readily.

**Comment by studentism** [comment]
SGE accepts similar directives to PBS, but not identical. Here are two semantically identical directives for joining input/output files that differ syntactically:

PBS:
#PBS -j oe

SGE:
#$ -j y

The directives will be ignored silently by the other submission manager, depending on which you use.

I have ready access to an SGE cluster that can be used for testing, but we'd have to jump through a couple hoops to get you direct access.

**Comment by sahilseth** [comment]
Great!

@studentism Do you have more such examples; potential issues with this file?
https://github.com/sahilseth/flowr/blob/devel/inst/conf/sge.sh

An option is that you could make such changes in a sge.sh file in your home, test them and let us know what works best. 

I usually test the simple sleep workflow (http://docs.flowr.space/install.html#test).
