### ISSUE TITLE
PBS scheduler errors with qsub submission: &amp;&amp; in bash command

### ISSUE THREAD

**Issue by dyndna** [sahilseth/flowr#8]
dependent jobs are failing because of syntax error while parsing first bash command:

```
PBS Job Id: 40993.
Job Name:   T95f3A8d9eG_001.job_start-1
Exec host:  
Execution terminated
Exit_status=2
resources_used.cput=00:00:00
resources_used.mem=0kb
resources_used.vmem=0kb
resources_used.walltime=00:00:01
```

#### sample 1, command 1:

    cat ~/flowr/runs/<SAMPLE_ID>/001../job_start_cmd_1.sh 
```
## --- command to run comes here (flow_mat)
## ------  
 mkdir -p 95f31dd1-0014-4f11-b866-f6bf5cb152c8__8d9ebd2e-9ac6-4d93-81fb-5cfe6f4a4e7a &amp;&amp; touch 95f31dd1-0014-4f11-b866-f6bf5cb152c8__8d9ebd2e-9ac6-4d93-81fb-5cfe6f4a4e7a.running 
```

    cat ~/flowr/runs/<SAMPLE_ID>/001../job_start_cmd_1.out

```
/var/spool/torque/mom_priv/jobs/40993....SC: line 35: syntax error near unexpected token `;&'
/var/spool/torque/mom_priv/jobs/40993.....SC: line 35: ` mkdir -p 95f31dd1-0014-4f11-b866-f6bf5cb152c8__8d9ebd2e-9ac6-4d93-81fb-5cfe6f4a4e7a &amp;&amp; touch 95f31dd1-0014-4f11-b866-f6bf5cb152c8__8d9ebd2e-9ac6-4d93-81fb-5cfe6f4a4e7a.running '
```

` &amp;&amp;` was passed in bash command and probable cause of error.

Subsequent jobs dependent on `job_start_cmd_1` fails:

```
PBS Job Id: 40994.
Job Name:  2_make_config
Aborted by PBS Server 
Job deleted as result of dependency on job 40993...
```

**Comment by sahilseth** [comment]
Is this still failing ?

**Comment by sahilseth** [comment]
I checked, for some reason the memory argument was empty:

```
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:05:00
#PBS -l mem=
```

```
fobj=readRDS("flow_details.rds")
fobj@jobs[[1]]@memory
character(0)
```

Can you check the flow_definition file it it has memory in the right format.

**Comment by sahilseth** [comment]
flow_def needs the following column names:
```
memory_reserved: amount of memory reserved
cpu_reserved: number of CPU reserved
```
It is a attempt to differentiate this from:

```
cpu_used
```
For example, one may reserve a node with 12 cores (cpu_reserved), but would like to use only 6 (cpu_used) due to memory restrictions. 

In future, would like to have both columns.

**Comment by sahilseth** [comment]
Yea, may be memory is shorter than memory_reserved.

I have added this:
https://github.com/sahilseth/flowr/commit/513263ca7767232ff412d222671f440a18643500

**Comment by sahilseth** [comment]
Ok, so the second issue was with rendering.

- Update the package
- replace `{{` with `{{{` as shown in: https://github.com/sahilseth/flowr/commit/f7bf959005b87a14a75102223518d47321a3353d in your torque.sh

I have tested this:
https://github.com/sahilseth/flowr/blob/master/inst/extdata/example1_flow_mat.txt

**Comment by dyndna** [comment]
Thanks and commit: f7bf959 is helpful to set up job scheduler config for more than one compute clusters.

Two minor issues:

* shell environment seems not passing correctly to compute nodes.

This requires me to hard code my individual commands and prefix `module load <module>` to make sure `env` has path to all required binaries and libraries. I see that my [torque.sh](https://github.com/sahilseth/flowr/blob/master/inst/conf/torque.sh#L8) has `#PBS -r y -V` flag. Not sure if `-V` can be supplied with array index or should be a new line.

* At [line 3 of torque.sh](https://github.com/sahilseth/flowr/blob/master/inst/conf/torque.sh#L3), does `#PBS -l nodes={{{NODES}}}:` takes character vector? Although not intuitive, one of our compute nodes needs character and not numeric vector for number of nodes! If I supply character vector in `flow_def.txt` under column: *nodes_reserved*, I see following in flowr submitted commands:

```
./002.make_config/make_config_cmd_1.sh:3:#PBS -l nodes=1:ppn=2
./003.chr/chr_cmd_16.sh:3:#PBS -l nodes=1:ppn=2
...
```

Thanks

**Comment by sahilseth** [comment]
Yes character vector is now supported. Can you try this with a column `nodes` instead of `nodes_reserved`.

I am going to make this simpler, for now this is what we have:

|flow_def_column |hpc_script_variable |
|:---------------|:-------------------|
|nodes           |NODES               |
|cpu_reserved    |CPU                 |
|memory_reserved |MEMORY              |
|email           |EMAIL               |
|walltime        |WALLTIME            |
|extra_opts      |EXTRA_OPTS          |
|*               |JOBNAME             |
|*               |STDOUT              |
|*               |CWD                 |
|*               |DEPENDENCY          |
|*               |TRIGGER             |
|**              |CMD                 |

\*: These are generated on the fly
\**: This is gathered from flow_mat

**Comment by sahilseth** [comment]
Good to know, it works now !

**Comment by sahilseth** [comment]
Hi @dyndna, I personally was not using/changing nodes variable, and seems had dropped it out of `to_flow()` function.

I can confirm that it works now using this example:

```
exdata = file.path(system.file(package = "flowr"), "extdata")
flow_mat = read_sheet(file.path(exdata, "example1_flow_mat.txt"))
flow_def = read_sheet(file.path(exdata, "example1_flow_def2.txt"))
fobj = suppressMessages(to_flow(flow_mat, def = flow_def, platform = "torque"))
fobj[[1]]@jobs[[1]]@nodes
fobj = submit_flow(fobj)
```


Sorry for the confusion.

links:
def: https://github.com/sahilseth/flowr/blob/master/inst/extdata/example1_flow_def2.txt
change in to_flow: https://github.com/sahilseth/flowr/commit/db0d3c67816db8f01a2e36215834e0b280f398c5?diff=split
