### ISSUE TITLE
How to integrate flowr and dplyr

### ISSUE THREAD

**Issue by harryprince** [sahilseth/flowr#88]
I am heavy using dplyr and sparklyr, flowr looks so great on workflow.

Could I translate my exist dplyr and sparklyr pipeline into flowr?

**Comment by sahilseth** [comment]
flowr submits jobs to the cluster. Certainly, if you have individual scripts for each step of your pipeline, you can submit them using flowr. Do you have an example workflow you want to convert to flowr?
