### ISSUE TITLE
modifying commands/resources before re-running

### ISSUE THREAD

**Issue by wisekh6** [sahilseth/flowr#90]
Hi Sahil,

Sometimes, a flowr pipeline can stop  because of insufficient memory/walltime (I set up) or inappropriate commands, and therefore they need to be revised before re-running. But, I am not sure about which flowr file (flow_details.rds?) I should modify in order to update the commands/memory/walltime. Would you give me your comments on this?

Thanks,

**Comment by sahilseth** [comment]
Was able to touch-base with Hoon and resolve this.
