### ISSUE TITLE
docs.flowr.space domain expired

### ISSUE THREAD

**Issue by meowcat** [sahilseth/flowr#93]
The domain name for the docs now displays some ads and a notice that it expired on 03-30:
http://docs.flowr.space/

**Comment by sahilseth** [comment]
Thanks for pointing it out. The docs should be back online in a few hours.

Its less than ideal, but all the docs are served from this repo, and the Rmd file should help:
https://github.com/sahilseth/flowr/blob/gh-pages/install.Rmd

Thanks!

**Comment by sahilseth** [comment]
we got it back online a few days ago, thanks!
